username = "root"
password = "R3unite123"
dbhostname = "localhost"
dbusername = "root"
dbpassword = "R3unite123"
dbname = "reunite"
video_path = "/var/www/html/video"
photo_path = "/var/www/html/photo"